permissions:
  web_search:
    - WebResearcher
  pdf_extract:
    - WebResearcher
  html_scraper:
    - WebResearcher
  consolidate_memory:
    - MemoryManager
  retrieve_memory:
    - MemoryManager
    - WebResearcher
    - CodeResearcher
  fact_check:
    - Evaluator
  code_interpreter:
    - CodeResearcher
  github_search:
    - CodeResearcher
  knowledge_graph_search:
    - Supervisor
    - WebResearcher

