version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - "16686:16686"
      - "14250:14250"

  weaviate:
    image: semitechnologies/weaviate:1.30.5
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      DEFAULT_VECTORIZER_MODULE: none
      DISABLE_TELEMETRY: "true"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
    volumes:
      - weaviate_data:/var/lib/weaviate

  otel-collector:
    image: otel/opentelemetry-collector:0.96.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    environment:
      ENVIRONMENT: ${ENVIRONMENT:-dev}
      SERVICE_VERSION: ${SERVICE_VERSION:-0.1.0}
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger
    restart: unless-stopped

  episodic-memory:
    build: .
    image: agentic/research-engine:latest
    command: uvicorn services.episodic_memory.app:app --host 0.0.0.0 --port 8081 --workers ${WORKER_COUNT:-4}
    environment:
      WORKER_COUNT: ${WORKER_COUNT:-4}
    ports:
      - "8081:8081"
    depends_on:
      - otel-collector
      - weaviate

volumes:
  weaviate_data:
