# External Secrets Operator Configuration
# Classification: CRITICAL - SECRETS MANAGEMENT
# Last Updated: 2025-08-08

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: orchestrix-pilot
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
---
# External Secret for Application Secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: application-secrets
  namespace: orchestrix-pilot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: application-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DATABASE_URL: "{{ .database_url }}"
        REPUTATION_API_KEYS: "{{ .reputation_api_keys }}"
  data:
  - secretKey: database_url
    remoteRef:
      key: orchestrix-pilot/application
      property: database_url
  - secretKey: reputation_api_keys
    remoteRef:
      key: orchestrix-pilot/application
      property: reputation_api_keys
---
# External Secret for LLM API Keys (to be populated separately)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llm-api-secrets
  namespace: orchestrix-pilot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: llm-api-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        LLM_API_KEY: "{{ .llm_api_key | default \"\" }}"
        OPENAI_API_KEY: "{{ .openai_api_key | default \"\" }}"
  dataFrom:
  - extract:
      key: orchestrix-pilot/llm-keys
---
# External Secret for GitHub Integration
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-secrets
  namespace: orchestrix-pilot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: github-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        GITHUB_TOKEN: "{{ .github_token | default \"\" }}"
  dataFrom:
  - extract:
      key: orchestrix-pilot/github-integration
---
# External Secret for Monitoring Stack
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: monitoring-secrets
  namespace: orchestrix-pilot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: grafana-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-password: "{{ .grafana_admin_password }}"
  data:
  - secretKey: grafana_admin_password
    remoteRef:
      key: orchestrix-pilot/monitoring
      property: grafana_admin_password