apiVersion: v1
kind: Service
metadata:
  name: agent-services
spec:
  selector:
    app: agent-services
    color: {{ .Values.color }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
