name: CD

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        required: false
        default: ''
      environment:
        description: 'Target environment'
        required: true
        default: 'production'

jobs:
  deploy-staging:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y curl gnupg software-properties-common
          curl -fsSL https://apt.releases.hashicorp.com/gpg | \
            sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
            sudo tee /etc/apt/sources.list.d/hashicorp.list
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          echo 'deb https://baltocdn.com/helm/stable/debian/ all main' | \
            sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install -y helm terraform
      - name: Deploy to staging
        run: |
          bash scripts/deploy.sh staging ${{ github.sha }}

  promote-production:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y curl gnupg software-properties-common
          curl -fsSL https://apt.releases.hashicorp.com/gpg | \
            sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
            sudo tee /etc/apt/sources.list.d/hashicorp.list
          curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
          echo 'deb https://baltocdn.com/helm/stable/debian/ all main' | \
            sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install -y helm terraform
      - name: Deploy to production
        run: |
          IMAGE_TAG=${{ inputs.image_tag }}
          if [ -z "$IMAGE_TAG" ]; then IMAGE_TAG=${{ github.sha }}; fi
          bash scripts/deploy.sh production "$IMAGE_TAG"
