name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pre-commit install
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Run tests
        run: pytest -v
      - name: Check codex queue
        run: |
          python scripts/codex_task_runner.py --preview > /tmp/queue.yml
          diff -u .codex/queue.yml /tmp/queue.yml

  codex-sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Check AGENTS.md exists
        run: test -f AGENTS.md
      - name: Setup environment
        run: bash scripts/agent-setup.sh
      - name: Run linters
        run: pre-commit run --all-files
      - name: Run tests
        run: pytest -q
