name: Weekly Dependency Audit

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Run pip-audit
        id: audit
        run: |
          pip-audit -r requirements.txt -f json -o pip_audit_report.json
        continue-on-error: true
      - name: Create issue if vulnerabilities found
        if: steps.audit.outcome == 'failure'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: 'Dependency audit detected vulnerabilities'
          content-filepath: pip_audit_report.json
          labels: security, dependencies
