name: Evaluator Training

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Install deps
        run: pip install -r requirements.txt -c constraints.txt
      - name: Run training
        run: python scripts/train_evaluator.py --epochs 1 --version ci-test
      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: evaluator-model
          path: models/evaluator/ci-test
