name: Integration Benchmarks

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-browsecomp-benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - name: Setup environment
        run: bash scripts/agent-setup.sh
      - name: Run BrowseComp benchmark harness
        env:
          HARNESS_TIMEOUT: '60'
          HARNESS_RETRIES: '1'
          HARNESS_RETRY_DELAY: '0.5'
        run: python tests/benchmarks/integration_harness.py
