name: Judge Pipeline

on:
  push:
    paths:
      - 'pipelines/judge/**'
      - 'data/golden_judge_dataset/**'
  pull_request:
    paths:
      - 'pipelines/judge/**'
      - 'data/golden_judge_dataset/**'
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  judge-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Setup environment
        run: bash scripts/agent-setup.sh
      - name: Run judge pipeline contract tests
        id: run-judge
        continue-on-error: true
        run: |
          set -o pipefail
          pytest pipelines/judge/tests -v | tee judge.log
          echo "exitcode=${PIPESTATUS[0]}" >> "$GITHUB_OUTPUT"
      - name: Upload test log
        uses: actions/upload-artifact@v4
        with:
          name: judge-test-log
          path: judge.log
      - name: Summarize failures
        if: always()
        run: python scripts/ci_summary.py judge.log coverage.xml ci_summary.md
      - name: Upload CI summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-summary
          path: ci_summary.md
      - name: Fail if tests failed
        if: steps.run-judge.outputs.exitcode != '0'
        run: exit 1
